title: VoyagerX
subtitle: Dev Blog
minimal_mistakes_skin: default
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
paginate: 5
paginatepath: /page:num/
include:
  - _pages

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://v6x.github.io" 

# Build settings
remote-theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

logo: "assets/images/logo.png"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

words_per_minute: 180

comments:
  provider: "disqus"
  disqus:
    shortname: "v6x-blog"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-122633049-7"
